jwt:
  secret: ${JWT_SECRET}
server:
  error:
    path: /user/error
    whitelabel:
      enabled: false
      
spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

application:
  title: ClearBalance
  version: 1.0
  
twilio:
  from-number: ${FROM_NUMBER}
  sid-key: ${SID_KEY}
  token-key: ${TOKEN_KEY}

frontend:
  url: ${FRONTEND_URL:http://localhost:4200}

  