# Database
MYSQL_USERNAME: root
MYSQL_PASSWORD: admin
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: clearbalance

# Server Config
CONTAINER_PORT: 8085
ACTIVE_PROFILE: prod

# Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}

UI_APP_URL: http://localhost:4200

JWT_SECRET: mysecuresecret